MalformedURLException: no protocol: shahnishit/jenkins-go-docker. I guess sine the registry doesn't yet exist, it cant use it. Changed to 'shahnishit/go-artifact'